require("transparent").setup({
  enable = true, -- boolean: enable transparent
  extra_groups = 'all', --{ -- table/string: additional groups that should be cleared
 --  extra_groups = { --{ -- table/string: additional groups that should be cleared
 --    -- In particular, when you set it to 'all', that means all available groups
 --
 --    --example of akinsho/nvim-bufferline.lua
 --    -- "nvim_tree_highlight",
 --    "Normal",
 --    "NvimTreeNormal",
 --    "NvimNotifyRefreshHighlights",
 --    "BufferLineTabClose",
 --    "BufferlineBufferSelected",
 --    "BufferLineFill",
 --    "BufferLineBackground",
 --    "BufferLineSeparator",
 --    "BufferLineIndicatorSelected",
 --    "NotifyERRORBody",
 --    "NotifyWARNBody",
 --    "NotifyINFOBody",
 --    "NotifyDEBUGBody",
 --    "NotifyTRACEBody",
 --    "background_colour",
 --    "NotifyLogTime",
 --    "NotifyLogTitle",
 -- },
 exclude = {
            "lualine_x_diff_modified_terminal",
            "lualine_x_diff_modified_inactive",
            "lualine_x_diff_modified_replace",
            "lualine_x_diff_modified_command",
            "lualine_x_diff_modified_visual",
            "lualine_x_diff_modified_normal",
            "lualine_x_diff_modified_insert",
            "lualine_x_diff_removed_terminal",
            "lualine_x_diff_removed_inactive",
            "lualine_x_diff_removed_replace",
            "lualine_x_diff_removed_command",
            "lualine_x_diff_removed_visual",
            "lualine_x_diff_removed_normal",
            "lualine_x_diff_removed_insert",
            "lualine_x_diff_added_terminal",
            "lualine_x_diff_added_inactive",
            "lualine_x_diff_added_replace",
            "lualine_x_diff_added_command",
            "lualine_x_diff_added_visual",
            "lualine_x_diff_added_normal",
            "lualine_x_diff_added_insert",
            "lualine_a_terminal",
            "lualine_a_inactive",
            "lualine_a_replace",
            "lualine_a_command",
            "lualine_a_visual",
            "lualine_a_normal",
            "lualine_a_insert",
            "lualine_b_terminal",
            "lualine_b_inactive",
            "lualine_b_replace",
            "lualine_b_command",
            "lualine_b_visual",
            "lualine_b_normal",
            "lualine_b_insert",
            "lualine_c_terminal",
            "lualine_c_inactive",
            "lualine_c_replace",
            "lualine_c_command",
            "lualine_c_visual",
            "lualine_c_normal",
            "lualine_c_insert",
            "CursorColumn",
            "CursorLine",
            "CursorLineSign",
            "CursorLineFold",
            "NvimTreeCurosrColumn",
            "NvimTreeCursorLine",
            "NvimTreeCursorLineNr",

          },
})
